import "server-only";

import { createServerSupabase } from "@/core/db/server";

import { sessionIpHashSalt } from "./env";
import { parseAuthLinkParams } from "./link-params";
import { LOGIN_PATH, SET_PASSWORD_PATH } from "./paths";
import { sessionMetaFrom } from "./request-meta";

/**
 * Auth links (recovery, and invite since 1.3) land on `/auth/confirm?token_hash=…&type=…` and
 * are verified server-side with `verifyOtp` (ADR-0012): no PKCE verifier cookie is needed, so a
 * link generated by the bootstrap script or opened on another device works.
 *
 * Since the 3cB review the link's GET only shows a "Continue to MaxOff" page; this runs behind
 * the page's POST (`confirmAuthLink` in `actions.ts`). A chat drawing a link preview or a mail
 * scanner fetches the GET, and a one-time token spent by a fetch is a link the person can never
 * open, so nothing verifies until they tap.
 *
 * A verified link opens a full session, so this is where the member is checked and the
 * login recorded: someone who is not an active member is signed out again at once (GoTrue
 * issues recovery links to any auth user, it knows nothing about `members`), and an active
 * member gets their `session_events(login)` row here, whether or not they go on to set a
 * password. Returns where the caller should send the browser next.
 */

export const EXPIRED_LINK_PATH = `${LOGIN_PATH}?reason=link`;

export const INACTIVE_LINK_PATH = `${LOGIN_PATH}?reason=inactive`;

export async function verifyAuthLink(params: {
  tokenHash: string | null;
  type: string | null;
  headers: Headers;
}): Promise<string> {
  const link = parseAuthLinkParams(params);
  if (!link) return EXPIRED_LINK_PATH;

  const supabase = await createServerSupabase();
  const { data, error } = await supabase.auth.verifyOtp({
    type: link.type,
    token_hash: link.tokenHash,
  });
  const userId = data.user?.id;
  if (error || !userId) return EXPIRED_LINK_PATH;

  // RLS hides the row from anyone not active, so the status comes from member_self_status().
  const { data: status, error: memberError } = await supabase.rpc("member_self_status");
  if (memberError) throw memberError;

  // A link is the one way an invited person opens a session (WORKFLOWS §1a): no login row yet
  // (session_login() needs an active member); setPassword() accepts the invite and records the
  // login. A recovery link counts too: GoTrue confirms the auth user the first time any link is
  // opened, after which only recovery tokens can be issued, and "Forgot password" then works as
  // the self-serve way back to /set-password. Deactivated or unknown people stay out.
  if (status === "invited") return SET_PASSWORD_PATH;
  if (status !== "active") {
    await supabase.auth.signOut({ scope: "local" });
    return INACTIVE_LINK_PATH;
  }

  const { userAgent, ipHash } = await sessionMetaFrom(params.headers, sessionIpHashSalt());
  const { error: loginError } = await supabase.rpc("session_login", {
    ...(userAgent ? { user_agent: userAgent } : {}),
    ...(ipHash ? { ip_hash: ipHash } : {}),
  });
  if (loginError) {
    await supabase.auth.signOut({ scope: "local" });
    throw loginError;
  }

  return SET_PASSWORD_PATH;
}
